import { Router } from "express";
import * as c from "../controllers/ai.js";
import { requireAuth } from "../middleware/auth.js";
import { aiLimiter } from "../middleware/rateLimiters.js";
const r = Router();
r.use(requireAuth);
r.get("/insights", aiLimiter, c.insights);
r.post("/chat", aiLimiter, c.chat);
r.get("/conversations", c.conversations);
r.post("/conversations", c.createConversation);
r.get("/conversations/:id", c.conversation);
r.patch("/conversations/:id", c.renameConversation);
r.delete("/conversations/:id", c.deleteConversation);
r.get("/weekly-report", c.weeklyReport);
r.post("/weekly-report", c.weeklyReport);
r.post("/daily-practice", c.dailyPractice);
r.get("/recommendations", c.aiRecommendations);
r.get("/roadmap", c.roadmap);
export default r;
