import { Router } from "express";
import * as c from "../controllers/auth.js";
import { requireAuth } from "../middleware/auth.js";
import { authLimiter, otpLimiter } from "../middleware/rateLimiters.js";
const router = Router();
router.post("/register", authLimiter, c.register);
router.post("/verify-email", otpLimiter, c.verifyEmail);
router.post("/resend-otp", otpLimiter, c.resendOtp);
router.post("/login", authLimiter, c.login);
router.post("/logout", c.logout);
router.get("/me", requireAuth, c.me);
router.post("/forgot-password", authLimiter, c.forgotPassword);
router.post("/reset-password", authLimiter, c.resetPassword);
router.post("/change-password", requireAuth, authLimiter, c.resetPassword);
export default router;
