export const ROUTES = {
  HOME: '/',
  FEATURES: '/features',
  HOW_IT_WORKS: '/how-it-works',
  ABOUT: '/about',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CONNECT_CODEFORCES: '/connect-codeforces',
  VERIFY_CODEFORCES: '/verify-codeforces',
  NOT_FOUND: '/404',

  DASHBOARD: '/app/dashboard',
  ANALYTICS: '/app/analytics',
  ANALYTICS_RATING: '/app/analytics/rating',
  ANALYTICS_DIFFICULTY: '/app/analytics/difficulty',
  ANALYTICS_TOPICS: '/app/analytics/topics',
  ANALYTICS_SUBMISSIONS: '/app/analytics/submissions',
  ANALYTICS_CONTESTS: '/app/analytics/contests',
  PROBLEMS: '/app/problems',
  PROBLEMS_RECOMMENDED: '/app/problems/recommended',
  PROBLEMS_HISTORY: '/app/problems/history',
  DAILY_PRACTICE: '/app/daily-practice',
  AI_COACH: '/app/ai-coach',
  ROADMAP: '/app/roadmap',
  PROGRESS: '/app/progress',
  CONTESTS: '/app/contests',
  PROFILE: '/app/profile',
  SETTINGS: '/app/settings',
};
